config/routes.rb
Rails.application.routes.draw do
  authenticate :admin do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :users, path_names: { sign_up: "" }, controllers: {
    registrations: "users/registrations",
    invitations: "users/invitations"
  }

  devise_for :admins, path_names: { sign_up: "" }

  authenticate do
    resources :statuses, except: %i[ index ]
    resources :users, param: :username, only: %i[show index]
  end

  root "statuses#index"
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: %i[ show edit update destroy ]
  before_action :confirm_ownership, only: %i[ update destroy edit ]

  # GET /statuses or /statuses.json
  def index
    @users = User.active.preload(:current_status)
  end

  # GET /statuses/1 or /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses or /statuses.json
  def create
    @status = Status.new(**status_params, user: current_user)

    respond_to do |format|
      if @status.save
        format.html { redirect_to status_url(@status), notice: "Status was successfully created." }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1 or /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to status_url(@status), notice: "Status was successfully updated." }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1 or /statuses/1.json
  def destroy
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url, notice: "Status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    def confirm_ownership
      return head :unauthorized unless @status.user.eql?(current_user)
    end

    # Only allow a list of trusted parameters through.
    def status_params
      params.require(:status).permit(:content)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_blank_status.html.erb
<div class="card">
  <div class="card-content">
    <div class="media">
      <% if user.avatar.attached? %>
        <div class="media-left">
          <%= image_tag(user.avatar.variant(:thumb), size: "64x64", class: "image is-64x64") %>
        </div>
      <% end %>
      <div class="media-content">
        <div class="title is-4">
          <%= link_to user do %>
            <%= user.username %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="content">
      No status yet!
    </div>
  </div>
</div>

app/views/statuses/_form.html.erb
<%= form_with(model: status) do |form| %>
  <% if status.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <%= pluralize(status.errors.count, "error") %> prohibited this status from being saved
      </div>

      <div class="message-body">
        <ul>
          <% status.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div>
    <%= form.label :content, class: "label" %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.submit "Create status", class: "button is-primary" %>
  </div>
<% end %>

app/views/statuses/_status.html.erb
<div class="card">
  <div class="card-content">
    <div class="media">
      <% if status.user.avatar.attached? %>
        <div class="media-left">
          <%= image_tag(status.user.avatar.variant(:bigger_thumb), size: "96x96", class: "image is-96x96") %>
        </div>
      <% end %>
      <div class="media-content">
        <div class="title is-4">
          <%= link_to status.user do %>
            <%= status.user.username %>
          <% end %>
        </div>
        <div class="subtitle is-6">
          <%= time_tag status.created_at do %>
            <span>
              shared <%= time_ago_in_words status.created_at %> ago
            </span>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card-content">
      <%= status.content %>
    </div>
    <% if status.user.eql? current_user %>
      <div class="card-footer">
        <div class="card-footer-item">
          <%= link_to "Edit status", edit_status_path(status) %>
        </div>
        <div class="card-footer-item">
          <%= link_to "Delete status", status, method: :delete %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/statuses/edit.html.erb
<%= render "form", status: @status %>

<br>

<div>
  <%= link_to "Back", :back, class: "button is-link" %>
</div>

app/views/statuses/index.html.erb
<div id="statuses">
  <% @users.each do |user| %>
    <div class="section">
      <% if user.current_status.present? %>
        <%= render user.current_status %>
      <% else %>
        <%= render partial: "statuses/blank_status", locals: { user: user } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/statuses/new.html.erb
<div class="title">New status</div>

<%= render "form", status: @status %>

<br>

<div class="subtitle">
  <%= link_to "Back to statuses", statuses_path %>
</div>

app/views/statuses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @status %>