config/routes.rb
Rails.application.routes.draw do
  authenticate :admin do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :users, path_names: { sign_up: "" }, controllers: {
    registrations: "users/registrations",
    invitations: "users/invitations"
  }

  devise_for :admins, path_names: { sign_up: "" }

  authenticate do
    resources :statuses, except: %i[ index ]
    resources :users, param: :username, only: %i[show index]
  end

  root "statuses#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionView::Helpers::UrlHelper
  
  before_action :authenticate_user!, unless: -> { current_page?(root_path) }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<% unless flash.empty? %>
  <div class="container">
    <% if flash.notice.present? %>
      <div class="notification is-info">
        <%= notice %>
      </div>
    <% end %>
    <% if flash.alert.present? %>
      <div class="notification is-danger">
        <%= alert %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<div class="navbar is-fixed-top mb-2">
  <div class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item">
        <%= button_to "Home", root_path, method: :get, class: "button is-primary" %>
      </div>
      <% if user_signed_in? %>
        <div class="navbar-item">
          <%= button_to "Create status", new_status_path, method: :get, class: "button is-warning" %>
        </div>
      <% else %>
        <div class="navbar-item">
          <%= button_to "Login", new_user_session_path, method: :get, class: "button is-warning" %>
        </div>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="navbar-end">
        <div class="navbar-item">
          <%= link_to user_path(current_user), class: "tag is-large" do %>
            <%= image_tag(current_user.avatar.variant(:thumb), size: "24x24", class: "image is-24x24 mr-2") if current_user.avatar.attached? %>
            <%= current_user.username %>
          <% end %>
        </div>
        <div class="navbar-item">
          <%= button_to "Edit", edit_user_registration_path, method: :get, class: "button is-info", disabled: current_page?(edit_user_registration_path) %>
        </div>
        <div class="navbar-item">
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "button is-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>